//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace stok_takip.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMalGiris
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblMalGiris()
        {
            this.tblSatis = new HashSet<tblSatis>();
        }
    
        public int ID { get; set; }
        public string Marka { get; set; }
        public string Tur { get; set; }
        public Nullable<int> Amper { get; set; }
        public string Hurda { get; set; }
        public string Tarih { get; set; }
        public Nullable<int> Fiyat { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSatis> tblSatis { get; set; }
    }
}
