//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace stok_takip.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSatis
    {
        public int ID { get; set; }
        public Nullable<int> SatilanID { get; set; }
        public string Odeme { get; set; }
        public string Tarih { get; set; }
    
        public virtual tblMalGiris tblMalGiris { get; set; }
    }
}
