//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace stok_takip.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_2
    {
        public int ID { get; set; }
        public string Tur { get; set; }
        public string Marka { get; set; }
        public Nullable<int> Amper { get; set; }
        public string Hurda { get; set; }
        public string Tarih { get; set; }
        public Nullable<int> Fiyat { get; set; }
    }
}
